### PR TITLE
Updated the UI of main.py

### PR DESCRIPTION
**Pull request by sarthakd999**

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
Can u attach the image of the updated UI. @sarthakd999

**Comment by swapnilsparsh** [comment]
If possible attach the image of the updated UI.
@sarthakd999

**Comment by sarthakd999** [comment]
okk 
@swapnilsparsh

**Comment by sarthakd999** [comment]
I have added the image in the images folder
It is in .png Format

@swapnilsparsh

**Comment by sarthakd999** [comment]
It is with name IPL_final.png 

@swapnilsparsh

**Comment by swapnilsparsh** [comment]
You have done great job but you have removed the Dark button and the application is not specified to IPL only , if possible fix these two issue and then make a PR again.@sarthakd999

**Comment by sarthakd999** [comment]
okay Sure
@swapnilsparsh

**Comment by sarthakd999** [comment]
Bro I have just changed the UI of main.py 
and you are talking about cricbuzz.py

@swapnilsparsh

**Comment by sarthakd999** [comment]
please do accept my requrst (PR)

@swapnilsparsh

**Comment by swapnilsparsh** [comment]
@sarthakd999 Add the Dark function which you have removed then I will accept the PR.

**Comment by sarthakd999** [comment]
okkk for sure

@swapnilsparsh

**Comment by sarthakd999** [comment]
Hi Captain @swapnilsparsh ,
I added The feature U wanted on your project

I also added an additional feature which i personally loved to code 

u can see the output images in the "images" folder  

normal_mode --> when in normal mode
dark_mode --> when in dark mode
 
and btw i updated the "main.py" file

so plz do convey a message about the new feature

Yours Truly Friend,
@sarthakd999

**Comment by sarthakd999** [comment]
plz accept my request
@swapnilsparsh

**Comment by sarthakd999** [comment]
Bro I have made efforts to do it just see to it plzz

@swapnilsparsh

**Comment by swapnilsparsh** [comment]
I will look into your PR but I am facing some problems at my end. Once it will get fixed I will surely look into your contribution.
@sarthakd999

**Comment by sarthakd999** [comment]
Okk 

But Plz check it as early as possible Bcoz time is running

@swapnilsparsh

**Comment by sarthakd999** [comment]
U didn't liked the UI of ur Project ???

@swapnilsparsh

**Comment by swapnilsparsh** [comment]
@sarthakd999 There is a error while running your code.
Fix that and then send the PR again

**Comment by sarthakd999** [comment]
Bro From my end there is no any error 

I will keep my code aside in a new file "IPL.py"

just check that once
@swapnilsparsh

**Comment by sarthakd999** [comment]
bro see to it the file name is "IPL.py"

@swapnilsparsh

**Comment by sarthakd999** [comment]
Please see to it faster bro 

@swapnilsparsh

**Comment by sarthakd999** [comment]
Because There is no any fault here 
From my end 

Btw what is the problem from ur end
@swapnilsparsh

**Comment by sarthakd999** [comment]
Have u seen the PR ???

@swapnilsparsh

**Comment by swapnilsparsh** [comment]
There is a error while running your code, fix the error and then resend the PR. @sarthakd999

**Comment by sarthakd999** [comment]
which code are u running can u please tell me ??

bcoz there is no any error in my code

Are u calling blue color an error??

@swapnilsparsh

**Pull request closed without merging**
