### PR TITLE
feature: Added automatic refresh feature

### PR DESCRIPTION
**Pull request by sauravsolanki**
1. Get the live score after every 2 sec
2. Added Doc to the function and single line comment for code
readability
3. Added exception handler for proper function of App

### CODE REVIEW

**Comment by sauravsolanki** [comment]
@swapnilsparsh Please check this PR.

**Comment by swapnilsparsh** [comment]
Resolve the conflict and resend the PR.

**Comment by sauravsolanki** [comment]
@swapnilsparsh Yes. Resolved.

**Comment by sauravsolanki** [comment]
@swapnilsparsh Is there any problem in this branch? Please let me know

**Comment by swapnilsparsh** [comment]
Resolve the Conflict and resend the PR

**Comment by sauravsolanki** [comment]
@swapnilsparsh Dear Author, Please merge the branch based on request queue else this conflict will keep rising every time if latest PR get merged.

**Comment by sauravsolanki** [comment]
@swapnilsparsh Please add hacktoberfest-accepted if you think my work is valid and according to Open Sources ethics.

**Comment by swapnilsparsh** [comment]
Ok, will check your PR in afternoon when live match will be played

**Comment by swapnilsparsh** [comment]
@sauravsolanki Ok, will check your PR in afternoon when live match will be played.

**Comment by sauravsolanki** [comment]
@swapnilsparsh Thank you bro. Please add hacktoberfest-accepted.

**Comment by swapnilsparsh** [comment]
@sauravsolanki Hacktoberfest Accepted

**Pull request merged**
