### PR TITLE
Fix result_score IndexError (issue #2)

### PR DESCRIPTION
**Pull request by IanFindlay**
The result_score parse was looking for a class that no longer exists (issue #2)  so I updated it to the current one. Similarly, the index of the scores themselves appeared to be wrong, so I've updated them.

To prevent IndexErrors breaking the program in the future, I've wrapped each of the parsing statements in try/except blocks.

Hopefully this is useful.

### CODE REVIEW

**Comment by IanFindlay** [comment]
The site has updated and now there is a live result score that can be used. I'm going to make it so it attempts to get a live result_score then, if there is no live game so no live message, attempts to get a finished result_score. Finally, if there is neither then it will catch the IndexError exceptions so it doesn't break.

Closing this PR until I make these changes.

**Comment by IanFindlay** [comment]
Hopefully, re-opening this pull request will add the latest changes mentioned above to it. If not, I'll make another.

**Comment by IanFindlay** [comment]
Conflict here due to the recent merge. Do you want me to maintain the new formatting that was done @swapnilsparsh ? I have never seen variables aligned like that in Python code and I am fairly sure it isn't PEP 8 compliant.

Decided to resolve the conflict and remove the odd formatting.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
You have solved the error but on clicking the refresh button, data is not getting updated.

**Comment by IanFindlay** [comment]
Sorry about that, accidentally deleted that section when I was resolving the conflict. It should work now, but I can't test it as the game is currently finished. At the very least, it is back to how it was with only the IndexError related code changed.

**Comment by swapnilsparsh** [comment]
> Sorry about that, accidentally deleted that section when I was resolving the conflict. It should work now, but I can't test it as the game is currently finished. At the very least, it is back to how it was with only the IndexError related code changed.

If the game is over then also it should show the score of the finished game.

**Comment by IanFindlay** [comment]
> If the game is over then also it should show the score of the finished game.

It does, but I can't test the refresh function on a game that is finished as there is nothing to be updated.

**Comment by swapnilsparsh** [comment]
> > If the game is over then also it should show the score of the finished game.
> 
> It does, but I can't test the refresh function on a game that is finished as there is nothing to be updated.

In order to merge your PR , I would like to do a small change here that you can change the lines of codes once again so that when I run the program it automatically fetch the current on going match score or the last active match score without pressing the refresh button

**Comment by IanFindlay** [comment]
> it automatically fetch the current on going match score or the last active match score without pressing the refresh button

Does it not already do this for you? When I run this on my local machine the latest match, whether it's finished or currently live, is displayed without having to press refresh.

**Comment by swapnilsparsh** [comment]
Thank you for Solving the Issue. @IanFindlay 👍🏼

**Pull request merged**
