### PR TITLE
Setup repair

### PR DESCRIPTION
**Pull request by Parthav46**
Related to #9
- Removed venv folder
- Removed .idea folder
- Added .gitignore
- Added setup scripts

### CODE REVIEW

**Comment by mangoomeh** [comment]
Pardon me for stupid question but what does a setup file do?

**Comment by Parthav46** [comment]
> Pardon me for stupid question but what does a setup file do?

It is used to setup your environment so that you don't need to remember what steps to follow and just start with the work.

**Comment by mangoomeh** [comment]
so all you need to do is to run the python script directly (like cd to the file directory and run python main,py)? And then the computer automatically reads the setup file and do the necessary pip installs and such?

**Comment by Parthav46** [comment]
No, you need to run (using powershell for Windows or terminal for Linux) this script whenever you clone the project and it will create venv and pip install all dependencies for you. Running the program is independent from this script.

**Pull request closed without merging**
