### PR TITLE
Fixed score refresh

### PR DESCRIPTION
**Pull request by shrn2**
The score gets refreshed every 2 seconds.

### CODE REVIEW

**Comment by shrn2** [comment]
@swapnilsparsh check this PR

**Comment by swapnilsparsh** [comment]
Resolve the conflict and resend the PR

**Comment by shrn2** [comment]
@swapnilsparsh resolved

**Comment by swapnilsparsh** [comment]
@tre3x Thanks you for contributing but the issue is already resolved.

**Pull request closed without merging**
